import type { Metadata } from "next";
import {Inter , Montserrat} from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/Nav/NavBar";

const inter = Inter({
  subsets: ["latin"],
  weight:["400" , "700"],
  variable: "--font-inter",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  weight:["400" , "700"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} dark antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
